# Скачивание файлов с wget и curl

1. Установите утилиты `wget` и `curl` в Вашей операционной системе, если не установлены.
2. С помощью утилиты `wget`, как в примерах ниже, скачайте сведения о запасах готовой продукции за разные периоды. Используйте ссылку для скачивания со страницы с запасами готовой продукции, которую можно получить при копировании URL-адреса для кнопки *Скачать*.

`wget`   утилита, используя для загрузки данных с внешних источников

Пример команды с переименованием получаемого файла

wget -O data.zip ftp://URL/1MB.zip
Пример команды с переименованием файла и обновлением метки времени согласно исходному файлу:

wget -o data.zip -N ftp://URL/1MB.zip
Пример команды с отключением проверки сертификата:

wget --no-check-certificate https://URL/somedata.txt
При вызове команды из блока кода в блокноте необходимо использовать символ ! перед командой как в примере ниже:

### Примеры с wget
#### Пример 1

In [1]:
!wget https://raw.githubusercontent.com/maryiad/ml-example/main/data/Zapasy_produkcii_2016_2017.csv

--2025-09-11 18:43:32--  https://raw.githubusercontent.com/maryiad/ml-example/main/data/Zapasy_produkcii_2016_2017.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3572 (3,5K) [text/plain]
Saving to: 'Zapasy_produkcii_2016_2017.csv'

     0K ...                                                   100% 2,88M=0,001s

2025-09-11 18:43:32 (2,88 MB/s) - 'Zapasy_produkcii_2016_2017.csv' saved [3572/3572]

#### Пример 2

In [2]:
!wget -O data.csv --no-check-certificate https://raw.githubusercontent.com/maryiad/ml-example/main/data/Zapasy_produkcii_2016_2017.csv

--2025-09-11 18:45:53--  https://raw.githubusercontent.com/maryiad/ml-example/main/data/Zapasy_produkcii_2016_2017.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3572 (3,5K) [text/plain]
Saving to: 'data.csv'

     0K ...                                                   100% 2,66M=0,001s

2025-09-11 18:45:54 (2,66 MB/s) - 'data.csv' saved [3572/3572]

#### Визуализация данных

In [3]:
import pandas as pd
dataF = pd.read_csv('Zapasy_produkcii_2016_2017.csv')

##### Визуализация данных на примере запросов продукции за 2016-2017 гг.

In [4]:
dataF.head()

             territory economyBranches    2016    2017
0    Брестская область  Промышленность  3659,7  3850,5
1    Витебская область  Промышленность   494,9   509,1
2   Гомельская область  Промышленность   327,8   365,5
3  Гродненская область  Промышленность   311,2   350,1
4             г. Минск  Промышленность   455,5   521,2

##### Визуализация данных на примере запросов продукции за 2000-2009 гг. (пример 1)

In [5]:
dataS = pd.read_csv("Zapasy_produkcii_2016_2017.csv")
dataS.head()

             territory economyBranches    2016    2017
0    Брестская область  Промышленность  3659,7  3850,5
1    Витебская область  Промышленность   494,9   509,1
2   Гомельская область  Промышленность   327,8   365,5
3  Гродненская область  Промышленность   311,2   350,1
4             г. Минск  Промышленность   455,5   521,2

#### Скачивание с помощью curl и визуализация

In [6]:
!curl -o samplefile.csv https://raw.githubusercontent.com/maryiad/ml-example/main/data/Zapasy_produkcii_2000_2009.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2128  100  2128    0     0   4787      0 --:--:-- --:--:-- --:--:--  4825

##### Визуализация данных на примере запросов продукции за 2000-2009 гг. (пример 2)

In [7]:
dataTh = pd.read_csv("samplefile.csv")

dataTh.head()

,territory,economyBranches,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,Брестская область,Промышленность,45096,79871,110418,172616,213923,232622,271186,386450,515204,570303
1,Витебская область,Промышленность,44753,79845,122775,143626,182935,248013,244190,298380,485347,404500
2,Гомельская область,Промышленность,53889,109230,138368,158192,216528,327949,357803,431234,563776,538487
3,Гродненская область,Промышленность,34040,65748,90248,98507,139022,166376,245326,335841,515213,576451
4,г. Минск,Промышленность,118765,223875,286673,356509,472380,532759,621840,739471,1300925,1714369

### Пример вставки изображения

In [3]:
from IPython.display import Image
Image(url='https://raw.githubusercontent.com/maryiad/ml-example/main/img/open-data-img.png')